# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelPackages = pkgs.linuxPackages_cachyos;
  boot.kernelModules = ["kvm-amd"];
  boot.kernelParams = ["nvidia-drm.fbdev=1"];
  boot.extraModulePackages = [];

  fileSystems."/data" = {
    device = "/dev/sda4";
    fsType = "ext4";
    options = ["noatime" "rw" "noexec"];
  };

  fileSystems."/persist".neededForBoot = true;
  fileSystems."/persist/home".neededForBoot = true;

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = false;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  #networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
