# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
      kernelModules = ["dm-snapshot" "amdgpu"];
    };
    # boot.kernelPackages = pkgs.linuxPackages_latest;
    kernelPackages = pkgs.linuxKernel.kernels.linux_xanmod_latest;
    kernelModules = ["kvm-amd" "amdgpu" "ntsync"];
    extraModulePackages = [];
    # kernelPatches = [
    #   {
    #     name = "amdgpu-ignore-ctx-privileges";
    #     patch = pkgs.fetchpatch {
    #       name = "cap_sys_nice_begone.patch";
    #       url = "https://github.com/Frogging-Family/community-patches/raw/master/linux61-tkg/cap_sys_nice_begone.mypatch";
    #       hash = "sha256-Y3a0+x2xvHsfLax/uwycdJf3xLxvVfkfDVqjkxNaYEo=";
    #     };
    #   }
    # ];
  };

  fileSystems."/data" = {
    device = "/dev/mapper/Bunk-data";
    fsType = "ext4";
    options = ["noatime" "rw" "noexec"];
  };

  fileSystems."/data/games" = {
    device = "/dev/mapper/Bunk-games";
    fsType = "ext4";
    options = ["noatime" "rw"];
  };

  fileSystems."/persist".neededForBoot = true;
  fileSystems."/persist/home".neededForBoot = true;

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = false; # lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp15s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
