# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  #TODO fix disko not working, using it for now
  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "usbhid" "virtio_pci" "virtio_scsi"];
      kernelModules = [];
    };
    kernelPackages = pkgs.linuxPackages_latest;
    kernelParams = ["net.ifnames=0"];
    extraModulePackages = [];
    tmp = {
      useTmpfs = true;
      tmpfsSize = "8G";
    };
  };

  # fileSystems."/".neededForBoot = true;

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/2ba400bb-3ec6-43a3-9661-0f2e5d109368";
      fsType = "xfs";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/A77B-82BC";
      fsType = "vfat";
      options = [
        "defaults"
        "nodev"
        "noexec"
        "nosuid"
        "dmask=0077"
        "fmask=0077"
      ];
    };
  };

  swapDevices = [];

  networking.useDHCP = true; # lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
